# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run python script

on:
  workflow_dispatch:

env:
  OPENAI_API_KEY : ${{secrets.OPENAI_API_KEY}}

jobs:
  run-python:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Run python file
      run: |
        pip3 install -r requirements.txt
        python3 src/main.py docs/handbook.pdf "What is the name of the company?" "Who is the CEO of the company?" "How many employees are there in this company?"
